-- Objects table
CREATE TABLE ora_lake_objects (
    object_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_name VARCHAR2(255),
    object_type VARCHAR2(50),
    content BLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    version NUMBER DEFAULT 1
);

-- Metadata table
CREATE TABLE ora_lake_metadata (
    meta_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id NUMBER REFERENCES ora_lake_objects(object_id),
    tag VARCHAR2(100),
    description CLOB,
    schema_hint CLOB
);
