-- Main objects table
CREATE TABLE ora_lake_objects (
    object_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_name   VARCHAR2(255) NOT NULL,
    object_type   VARCHAR2(100) NOT NULL,
    content       BLOB,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    version_num   NUMBER DEFAULT 1,
    CONSTRAINT uk_ora_lake_obj_name_type UNIQUE (object_name, object_type)
);

-- Metadata table
CREATE TABLE ora_lake_metadata (
    meta_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id    NUMBER REFERENCES ora_lake_objects(object_id) ON DELETE CASCADE,
    tag          VARCHAR2(255),
    description  CLOB,
    schema_hint  CLOB
);

-- Version history table
CREATE TABLE ora_lake_versions (
    version_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id    NUMBER REFERENCES ora_lake_objects(object_id) ON DELETE CASCADE,
    version_num  NUMBER,
    content      BLOB,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);